// "See FeeLure in Action" — a fully fictional, hand-authored illustrative
// example. NOT generated by Gemini and NOT a real website scan. It lives only
// on the Home page; nothing here is written to the community database.

const ADDON_AMOUNT = "₹149";
const FEE_AMOUNT = "₹99";
const TOTAL_EXTRA = "₹248";

export default function DemoShowcase() {
  return (
    <section
      className="border-y border-navy-100 bg-white py-16"
      aria-labelledby="demo-showcase"
    >
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="flex flex-wrap items-center gap-3">
          <h2
            id="demo-showcase"
            className="text-2xl font-extrabold text-navy-900 sm:text-3xl"
          >
            See FeeLure in Action
          </h2>
          <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold uppercase tracking-wide text-amber-800 ring-1 ring-amber-300">
            Illustrative demo — fictional checkout, not a real website or live
            AI scan
          </span>
        </div>
        <p className="mt-2 max-w-2xl text-sm text-navy-600">
          How FeeLure reads a checkout: this is a hand-written example of the
          kind of findings the community index documents. Every number here is
          fictional.
        </p>

        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          {/* LEFT — fictional checkout mockup */}
          <div className="overflow-hidden rounded-xl border border-navy-200 shadow-sm">
            <div className="flex items-center justify-between bg-navy-800 px-5 py-3">
              <span className="text-sm font-bold text-white">
                ShopFast India
              </span>
              <span className="rounded bg-navy-700 px-2 py-0.5 text-xs font-semibold text-navy-100">
                example only
              </span>
            </div>
            <div className="space-y-4 bg-navy-50 p-6">
              <div className="flex items-center justify-between rounded-lg border border-navy-100 bg-white p-4">
                <div>
                  <p className="font-bold text-navy-900">
                    SoundPulse Wireless Earbuds
                  </p>
                  <p className="text-xs text-navy-500">Black · 1 item</p>
                </div>
                <p className="text-lg font-extrabold text-navy-900">₹999</p>
              </div>

              <div className="flex items-start justify-between rounded-lg border-2 border-amber-300 bg-amber-50 p-4">
                <div>
                  <p className="flex items-center gap-2 font-bold text-navy-900">
                    Damage Protection Plan
                    <span className="rounded bg-amber-400 px-1.5 py-0.5 text-[10px] font-extrabold text-navy-900">
                      SELECTED FOR YOU
                    </span>
                  </p>
                  <p className="mt-1 text-xs text-navy-600">
                    <span
                      aria-hidden="true"
                      className="mr-1 inline-block h-3 w-3 translate-y-0.5 rounded-sm border-2 border-amber-500 bg-amber-400 align-middle"
                    />
                    Checkbox pre-ticked on the page
                  </p>
                </div>
                <p className="text-base font-extrabold text-navy-900">
                  {ADDON_AMOUNT}
                </p>
              </div>

              <div className="hidden items-center justify-between rounded-lg border border-navy-100 bg-white p-4 sm:flex">
                <div>
                  <p className="font-bold text-navy-900">Handling Fee</p>
                  <p className="text-xs text-navy-500">
                    In tiny grey text at the very last step
                  </p>
                </div>
                <p className="text-base font-extrabold text-navy-900">
                  {FEE_AMOUNT}
                </p>
              </div>

              <div className="flex items-center justify-between rounded-lg bg-navy-900 p-4">
                <p className="font-bold text-white">Order Total</p>
                <p className="text-xl font-extrabold text-amber-400">₹1,247</p>
              </div>

              <button
                type="button"
                tabIndex={-1}
                className="w-full cursor-default rounded-lg bg-amber-400 py-3 text-center font-bold text-navy-900"
              >
                Pay ₹1,247 now
              </button>
            </div>
          </div>

          {/* RIGHT — FeeLure-style analysis card */}
          <div className="rounded-xl border-2 border-navy-900 bg-white shadow-md">
            <div className="flex items-center justify-between rounded-t-xl bg-navy-900 px-5 py-3">
              <span className="flex items-center gap-2 text-sm font-extrabold text-white">
                <span
                  aria-hidden="true"
                  className="flex h-5 w-5 items-center justify-center rounded-full bg-amber-400 text-[11px] font-black text-navy-900"
                >
                  F
                </span>
                FeeLure analysis of this checkout
              </span>
              <span className="rounded bg-navy-700 px-2 py-0.5 text-xs font-semibold text-amber-300">
                demo findings
              </span>
            </div>
            <ul className="divide-y divide-navy-100">
              <li className="p-5">
                <div className="flex items-start justify-between gap-3">
                  <p className="font-bold text-navy-900">
                    Potential pre-selected add-on
                  </p>
                  <span className="shrink-0 rounded-md bg-amber-100 px-2 py-1 text-sm font-extrabold text-amber-800 ring-1 ring-amber-300">
                    {ADDON_AMOUNT}
                  </span>
                </div>
                <p className="mt-1.5 text-sm leading-relaxed text-navy-600">
                  Evidence: the &quot;Damage Protection Plan&quot; box is
                  already ticked next to{" "}
                  <span className="font-semibold text-navy-800">
                    &quot;SELECTED FOR YOU&quot;
                  </span>{" "}
                  — you are enrolled unless you actively untick it.
                </p>
              </li>
              <li className="p-5">
                <div className="flex items-start justify-between gap-3">
                  <p className="font-bold text-navy-900">
                    Late-disclosed handling fee
                  </p>
                  <span className="shrink-0 rounded-md bg-amber-100 px-2 py-1 text-sm font-extrabold text-amber-800 ring-1 ring-amber-300">
                    {FEE_AMOUNT}
                  </span>
                </div>
                <p className="mt-1.5 text-sm leading-relaxed text-navy-600">
                  Evidence: a{" "}
                  <span className="font-semibold text-navy-800">
                    &quot;Handling Fee&quot;
                  </span>{" "}
                  line appears only at the final step, in small grey text — it
                  was never part of the advertised ₹999 price.
                </p>
              </li>
              <li className="bg-navy-50 p-5">
                <div className="flex items-center justify-between">
                  <p className="font-extrabold text-navy-900">
                    Additional charges identified
                  </p>
                  <span className="rounded-md bg-navy-900 px-2.5 py-1 text-base font-extrabold text-amber-400">
                    {TOTAL_EXTRA}
                  </span>
                </div>
                <p className="mt-1 text-sm text-navy-600">
                  ₹999 advertised → ₹1,247 at payment: roughly 25% above the
                  headline price in this fictional example.
                </p>
              </li>
              <li className="p-5">
                <p className="flex items-start gap-2 text-sm font-semibold text-navy-800">
                  <svg
                    aria-hidden="true"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    className="mt-0.5 h-4 w-4 shrink-0 text-amber-500"
                  >
                    <path
                      fillRule="evenodd"
                      d="M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-7-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM9 9a.75.75 0 0 0 0 1.5h.253a.25.25 0 0 1 .244.304l-.459 2.066A1.75 1.75 0 0 0 10.747 15H11a.75.75 0 0 0 0-1.5h-.253a.25.25 0 0 1-.244-.304l.459-2.066A1.75 1.75 0 0 0 9.253 9H9Z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Suggested consumer action: review optional add-ons and the
                  final total before paying.
                </p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}
